export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const OBTENER_USUARIOS = 'OBTENER_USUARIOS'
export const USUARIO_ACTUAL = 'USUARIO_ACTUAL';
export const ACTUALIZAR_USUARIO= 'ACTUALIZAR_USUARIO';

export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const PRODUCTO_ACTUAL = 'PRODUCTO_ACTUAL';
export const ACTUALIZAR_PRODUCTO = 'ACTUALIZAR_PRODUCTO';

export const AGREGAR_VENTA = 'AGREGAR_VENTA';
export const OBTENER_VENTAS = 'OBTENER_VENTAS';

